### ISSUE TITLE
TypeError: quantize_dynamic() got an unexpected keyword argument 'activation_type'

### ISSUE THREAD

**Issue by arnabmanna619** [siddharth-sharma7/fast-Bart#5]
I am trying to replicate the code but I get an error related to `quantization`. I'm running it on Colab.

![image](https://user-images.githubusercontent.com/36996046/185759935-3547d32d-9aeb-4aa9-a6d6-3d9dbc04f855.png)

**Comment by Gooogr** [comment]
Faced with the same problem. Fixed issue by editing the requirements.txt file:
```
onnxruntime==1.7.0
```

**Comment by dangcaptkd2** [comment]
> onnxruntime==1.7.0
Thanks, this help me.

**Comment by DYF-AI** [comment]
You can comment the key 'activation_type'  to solve this problem.
